name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./dr/pom.xml
          mvn clean package -f ./response/pom.xml
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./kepco/pom.xml

      - name: Docker Build and push for Dr
        uses: docker/build-push-action@v4
        with:
          context: ./dr
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dr:latest
            ghcr.io/${{ github.repository }}/dr:${{ github.ref_name }}
            
      - name: Docker Build and push for Response
        uses: docker/build-push-action@v4
        with:
          context: ./response
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/response:latest
            ghcr.io/${{ github.repository }}/response:${{ github.ref_name }}
            
      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for Kepco
        uses: docker/build-push-action@v4
        with:
          context: ./kepco
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/kepco:latest
            ghcr.io/${{ github.repository }}/kepco:${{ github.ref_name }}
            
