apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepco
  labels:
    app: kepco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kepco
  template:
    metadata:
      labels:
        app: kepco
    spec:
      containers:
        - name: kepco
          image: "kxmjhwn/kepco:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
