---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr
  labels:
    app: dr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dr
  template:
    metadata:
      labels:
        app: dr
    spec:
      containers:
        - name: dr
          image: username/dr:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: response
  labels:
    app: response
spec:
  replicas: 1
  selector:
    matchLabels:
      app: response
  template:
    metadata:
      labels:
        app: response
    spec:
      containers:
        - name: response
          image: username/response:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: username/user:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepco
  labels:
    app: kepco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kepco
  template:
    metadata:
      labels:
        app: kepco
    spec:
      containers:
        - name: kepco
          image: username/kepco:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: dr
  labels:
    app: dr
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dr


---


apiVersion: v1
kind: Service
metadata:
  name: response
  labels:
    app: response
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: response


---


apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user


---


apiVersion: v1
kind: Service
metadata:
  name: kepco
  labels:
    app: kepco
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kepco

