apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr
  labels:
    app: dr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dr
  template:
    metadata:
      labels:
        app: dr
    spec:
      containers:
        - name: dr
          image: "kxmjhwn/dr:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
