apiVersion: apps/v1
kind: Deployment
metadata:
  name: response
  labels:
    app: response
spec:
  replicas: 1
  selector:
    matchLabels:
      app: response
  template:
    metadata:
      labels:
        app: response
    spec:
      containers:
        - name: response
          image: "kxmjhwn/response:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
